import type { Metadata } from "next";
import "@/app/globals.css";
import 'react-toastify/dist/ReactToastify.css';

import { Loader } from "@/app/components/loader/loader";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "GO GO NEXT",
  description: "Generated by create next app",
};

export default function LoginLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {

  console.log('>> render layout');

  return (
        <>
        <ToastContainer autoClose={1000}/>
          <div id="main-container">
            <Loader isActive={false}/>
            {children}
          </div>        
        </>
  );
}
