import type { Metadata } from "next";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';

import TopNav from "@/app/components/navigations/topnav";
import { Loader } from "@/app/components/loader/loader";
import { ToastContainer } from "react-toastify";
import { IsLogin } from '@/app/services/userService';


export const metadata: Metadata = {
  title: "GO GO NEXT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cl = IsLogin() ? 'pt-10' : '';

  return (
    <html lang="en">
      <body>
        <ToastContainer autoClose={1000}/>        
          <TopNav/>
          <div id="main-container" className={cl}>
            <Loader isActive={false}/>
            {children}
          </div>
          <footer className="text-center min-h-40 bg-gray-200">
            <p className="leading-10">Footer</p>
          </footer>     
      </body>
    </html>
  );
}
