import type { Metadata } from "next";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';

import { Loader } from "@/app/components/loader/loader";
import { ToastContainer } from "react-toastify";
import Navbar from "@/app/components/navigations/navbar";
// import { IsLogin } from "@/app/services/userService";

export const metadata: Metadata = {
  title: "GO GO NEXT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // console.log('>> LAYOUT> Login: ' + IsLogin());

  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <ToastContainer autoClose={1000}/>        
          
          <Navbar/>

          <div id="main">
            <div id="main-container" className='pt-10'>
              <Loader isActive={false}/>
              {children}
            </div>
          </div>
          <footer className="text-center min-h-40 bg-gray-200">
            <p className="leading-10">Footer</p>
          </footer>     
      </body>
    </html>
  );
}
