import type { Metadata } from "next";
import { Loader } from "@/app/components/loader/loader";


export const metadata: Metadata = {
  title: "GO GO NEXT",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div id="login-layout-container">
      <Loader isActive={false}/>
      {children}
    </div>   
  );
}
