import type { Metadata } from "next";
import { Loader } from "@/app/components/loader/loader";


export const metadata: Metadata = {
  title: "GO GO NEXT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <body>
          <div id="main-container">
            <Loader isActive={false}/>
            {children}
          </div>
      </body>
  );
}
